commentbin/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('commentbin.views',
    url(r'^$','index'),
    url(r'^about/','about'),
    url(r'^help/','sitehelp'),
    url(r'^logout/','logout'),
    url(r'^login/','login'),
    url(r'^(?P<snippet_id>\d+)/$','snippet'),
    url(r'^(?P<snippet_id>\d+)/comments/$','comments'),
    url(r'^(?P<snippet_id>\d+)/comments/(?P<comment_id>\d+)/$','comment'),
    )

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dj_intro_cs.views.home', name='home'),
    # url(r'^dj_intro_cs/', include('dj_intro_cs.foo.urls')),
    ('^_ah/warmup$', 'djangoappengine.views.warmup'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    ('^', include('commentbin.urls')),
)

commentbin/models.py
from django.db import models
from django.contrib.auth.models import User

class Snippet(models.Model):
  PYTHON='py'
  LATEX='tex'
  CPP='cpp'
  C='c'
  HTML='html'
  JAVASCRIPT='js'
  PHP = 'php'
  CSS = 'css'
  
  LANGUAGE_CHOICES = (
    ( PYTHON, 'Python' ),
    ( LATEX,  'LaTeX' ),
    ( CPP,    'C++' ),
    ( C,      'C'),
    ( HTML,   'HTML'),
    ( JAVASCRIPT, 'JavaScript'),
    ( PHP,    'PHP'),
    ( CSS,    'CSS (Cascading Style Sheets)'),
  )
  
  class Meta:
    ordering = ['creation_date']

  title = models.CharField(max_length=100,blank=True)
  code = models.TextField()
  formatted_html = models.TextField("cached pygment-formatted html version of the code",blank=True,editable=False,default=None)
  creation_date = models.DateTimeField(auto_now_add=True)
  nick = models.CharField(max_length=30,blank=True)
  user = models.ForeignKey(User,related_name='+',blank=True,null=True,on_delete=models.SET_NULL)
  public_comments = models.BooleanField("allow anyone to comment",default = True,help_text='If true, anyone can comment. Otherwise only the owner (if available), admin or the person with an access token can comment.' )
  visible_to_public = models.BooleanField("allow anyone to view",default = True,help_text='If false, the snippet will only be visible to the owner (if available) or anyone with the access token')
  owner_only_comments = models.BooleanField("only the owner can comment/delete",default = False,help_text='If true only the owner can comment. Note that the user must be known, otherwise no comments will be allowed')
  access_token = models.CharField(max_length=100,blank=True,default=None,help_text='The "master key" to the snippet. Its knowledge allows commenting, deleting and viewing the snippet.')
  language = models.CharField(max_length=4,choices = LANGUAGE_CHOICES,default=PYTHON)
  
  def format_code(self):
    from pygments import highlight
    from pygments.lexers import PythonLexer, HtmlLexer, JavascriptLexer, PhpLexer, TexLexer, CppLexer, CLexer, CssLexer
    from pygments.formatters import HtmlFormatter
    
    if self.language == self.PYTHON:
      lexer = PythonLexer()
    elif self.language == self.LATEX:
      lexer = TexLexer()
    elif self.language == self.CPP:
      lexer = CppLexer()
    elif self.language == self.C:
      lexer = CLexer()
    elif self.language == self.HTML:
      lexer = HtmlLexer()
    elif self.language == self.JAVASCRIPT:
      lexer = JavascriptLexer()
    elif self.language == self.PHP:
      lexer = PhpLexer()      
    elif self.language == self.CSS:
      lexer = CssLexer()
    
    self.formatted_html = highlight( self.code, lexer, HtmlFormatter(linenos=True) )
  
  def display_author(self):
    if self.user is not None:
      return self.user.username
    elif self.nick is not None:
      return self.nick
    else:
      return "anonymous"
    
  def __unicode__(self):
    return "Snippet #"+str(self.id)+":"+self.title;
  
  @models.permalink
  def get_absolute_url(self):
    return ('commentbin.views.snippet',(str(self.id)),{})
  
  def save(self,*args, **kwargs):
    if self.formatted_html is None:
      self.format_code()
    super(Snippet,self).save(kwargs)


class Comment(models.Model):
  class Meta:
    ordering = ['start','end']
  text = models.TextField("the (html) text of the comment")
  creation_date = models.DateTimeField(auto_now_add=True)
  nick = models.CharField(max_length=30,blank=True)
  user = models.ForeignKey(User,related_name='+',blank=True,null=True,on_delete=models.SET_NULL)
  snippet = models.ForeignKey(Snippet)
  replyto = models.ForeignKey('self',blank=True,null=True,default=None)
  start = models.IntegerField()
  end = models.IntegerField()
  inlinecomment = models.BooleanField("Is this an inline comment",default=True)
  access_token = models.CharField(help_text='The "master key" to the comment. Its knowledge allows deleting and modifying the comment.',max_length=100,blank=True,default=None)
  
  def __unicode__(self):
    return self.text
  
  def display_author(self):
    if self.user:
      return self.user.username
    elif self.nick:
      return self.nick
    else:
      return "anonymous"
  
  @models.permalink
  def get_absolute_url(self):
    return ('commentbin.views.comment',(str(self.snippet.id),str(self.id)))
  
  
# Create your models here.

commentbin/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.http import Http404, HttpResponseRedirect,HttpResponse
from django import forms
from django.template import RequestContext,Context,Template
from django.core import serializers
from django.core.urlresolvers import reverse as reverseurl
import django.contrib.auth as djangoauth

import json

from common.http import HttpNotImplemented,HttpPermissionDenied,HttpJSONResponse
import common.utils as utils
from commentbin.models import Snippet,Comment
import commentbin.auth as auth


class NewSnippetForm(forms.ModelForm):
  class Meta:
    model = Snippet
    
  initial = { 'nick':'anonymous', 'title':'Enter a title...', 'language':'py' }
  nick = forms.CharField(widget = forms.TextInput(attrs={'size':10, 'class':'nick_related', 'onClick':'javascript:textInputClick(this);', 'onBlur':'javascript:textInputLeave(this);'}))
  title = forms.CharField(widget = forms.TextInput(attrs={'onClick':'this.value=""'}))
      
def logout(request):
  djangoauth.logout(request)
  return HttpResponseRedirect(reverseurl('commentbin.views.index'))

def login(request):
  return HttpResponseRedirect(reverseurl('commentbin.views.index'))

def about(request):
  result = {'nick':request.session.get('nick','anonymous')}
  return render_to_response('about.html',result,context_instance=RequestContext(request))

def sitehelp(request):
  result = {'nick':request.session.get('nick','anonymous')}
  return render_to_response('sitehelp.html',result,context_instance=RequestContext(request))

def index(request):
  initial_values = NewSnippetForm.initial
  initial_values['nick'] = request.session.get('nick','anonymous') or 'anonymous'
  form = NewSnippetForm(request.POST or None, initial=initial_values)
  if request.method == 'POST':
    if form.is_valid():
      snip = form.save()
      append_token='';
      if request.user.is_authenticated():
	forms.user = request.user
      else:
	snip.user=None
	request.session['nick'] = snip.nick
	if not snip.visible_to_public or not snip.public_comments:
	  append_token='?access_token='+snip.access_token;
	if snip.access_token == '':
	  snip.access_token = auth.randomToken()
        request.session['snippet_access_token'] = snip.access_token
      if snip.title == 'Enter a title...':
	snip.title = ""
      snip.save()
      
      return HttpResponseRedirect(reverseurl('commentbin.views.snippet',args=[snip.id])+append_token)
  elif request.method != 'GET':
    raise HttpNotImplemented

  snippets = Snippet.objects.filter(visible_to_public=True).order_by('-creation_date')[:10]
  result = {'latest_snippets_list':snippets,
            'form':form,
            'nick':request.session.get('nick','anonymous')
            }
  utils.add_timestamp(result)
  return render_to_response('index.html',result,context_instance=RequestContext(request))


exportCommentFields = ("text","start","end", "user", "nick", "inlinecomment","creation_date")


def threadComments( c, comments ):
  replies = []
  for com in comments:
    if com.replyto == c:
      replies.append( threadComments( com, comments ) )
  return { 'comment':c,'replies':replies }

def thread( comments ):
  ret = []
  for c in comments:
    if c.replyto is None:
      ret.append(threadComments(c,comments))
  return ret

def flatten_thread( thread ):
  ret = []
  for element in thread:
    ret.append('indent')
    ret.append(element['comment'])
    if len(element['replies']) > 0:
      ret += flatten_thread( element['replies'])
    ret.append('deindent')
  return ret
  
                              
def snippet(request,snippet_id):
  try:
    snip = Snippet.objects.get(pk = snippet_id)
  except Snippet.DoesNotExist:
    raise Http404
  
  if snip.formatted_html is None:
    snip.format_code()
  
  if request.method == 'GET':
    params = {'snippet':snip,
              'nick':request.session.get('nick','anonymous') }
    utils.add_timestamp(params)
    
    if not auth.allow(request,snip,'view'):
      if 'access_token' in request.GET:
	params['wrong_password']=True
      return render_to_response('snippet-password.html',params,context_instance=RequestContext(request))

    
    try:
      inlinecomments = Comment.objects.filter(snippet = snip,inlinecomment=True)
      othercomments = Comment.objects.filter(snippet = snip,inlinecomment=False)
      params['comments'] = serializers.serialize("json",inlinecomments,ensure_ascii=False,fields=exportCommentFields);
      params['json-othercomments'] = serializers.serialize("json",othercomments,ensure_ascii=False,fields=exportCommentFields);
      params['threadedcomments'] = flatten_thread(thread((othercomments)))
    except Comment.DoesNotExist:
      pass

    params['show_delete_link'] = auth.allow(request,snip,'delete')
    params['show_comment_interface'] = auth.allow(request,snip,'add_comment')
    params['show_access_token'] = auth.allow(request,snip,'view_access_token')
    params['nick'] = request.session.get('nick','anonymous');
    
    return render_to_response('snippet.html',params,context_instance=RequestContext(request))
  elif request.method == 'DELETE':
    if not auth.allow(request,snip,'delete'):
      raise HttpPermissionDenied
    else:
      snip.delete()
      result = { "status":"Ok",
                 "redirect":reverseurl('commentbin.views.index') }
      return HttpJSONResponse(result)
  else:
    raise HttpNotImplemented

def commentFromRequest( request, snip ):
    if request.user.is_authenticated():
      u = request.user
    else:
      u = None
    auth.generateAccessTokenIfNotPresent(request)
    comment = Comment.objects.create( text = unicode(request.POST["text"]),
                                      start = int(request.POST["start"]),
                                      end = int(request.POST["end"]),
                                      nick = utils.getNick( request ) or "",
                                      user = u,
                                      snippet = snip,
                                      access_token = request.session['comment_access_token']);
    if comment.end == 0:
      comment.inlinecomment = False
    return comment

def comments(request,snippet_id):
  try:
    snip = Snippet.objects.get(pk = snippet_id)
  except Snippet.DoesNotExist:
    raise Http404
  
  if request.method == 'GET':
    try:
      from datetime import datetime
      created_after = datetime.fromtimestamp(int(float(request.GET["created_after"])))
    except:
      created_after = datetime.fromtimestamp(0)
    
    try:
      inlinecomments = Comment.objects.filter(snippet = snip, creation_date__gte = created_after, inlinecomment = True)
      othercomments = Comment.objects.filter(snippet = snip, creation_date__gte = created_after, inlinecomment = False)
  
      result = { "comments":serializers.serialize("json",inlinecomments,ensure_ascii=False,fields=exportCommentFields),
		 "othercomments":serializers.serialize("json",othercomments,ensure_ascii=False,fields=exportCommentFields),
                 "status":"Ok" }
    except:
      result = { "status":"Fail" }
      
    return HttpJSONResponse( result )

  
  elif request.method == 'POST':
    if not auth.allow(request,snip,'add_comment'):
      raise HttpPermissionDenied
    
    comment = commentFromRequest(request, snip)
    comment.save()

    request.session['nick'] = utils.getNick( request )
    result = { "comment":serializers.serialize("json",[comment],ensure_ascii=False,fields=exportCommentFields),
               "clientid":int(request.POST["id"]),
               'access_token':request.session['comment_access_token'],
               "status":"Ok" }
    return HttpJSONResponse( result )
  
  else:
    raise HttpNotImplemented

def comment(request,snippet_id,comment_id):
  try:
    snip = Snippet.objects.get(pk = snippet_id)
    comment = Comment.objects.get(pk = comment_id, snippet = snip)
  except:
    raise Http404

  if request.method == 'GET':
    if not auth.allow(request,comment,'view'):
      raise HttpPermissionDenied
    result = { "comment":serializers.serialize("json",[comment],ensure_ascii=False,fields=exportCommentFields),
               "status":"Ok" }
    if auth.allow(request,comment,'view_access_token'):
      result['access_token']=comment.access_token
    return HttpJSONResponse( result )
  
  elif request.method == 'PUT':
    utils.coerce_post(request)
    if not auth.allow(request, comment, 'change'):
      raise HttpPermissionDenied

    comment.text = request.PUT["text"]
    comment.start = int(request.PUT["start"])
    comment.end = int(request.PUT["end"])
    comment.save()
    
    result = { "comment":serializers.serialize("json",[comment],ensure_ascii=False,fields=exportCommentFields),
               "status":"Ok" }
    return HttpJSONResponse( result )
  
  elif request.method == 'DELETE':
    if not auth.allow(request,comment,'delete'):
      raise HttpPermissionDenied
    comment.delete()
    return HttpJSONResponse( {'status':'Ok', 'deletedID':comment_id} )

  elif request.method == 'POST':
    if not auth.allow(request,snip,'add_comment'):
      raise HttpPermissionDenied
    
    reply_comment = commentFromRequest(request,snip)
    reply_comment.replyto = comment
    reply_comment.save()
    request.session['nick'] = utils.getNick( request )
    result = { "comment":serializers.serialize("json",[reply_comment],ensure_ascii=False,fields=exportCommentFields),
               "clientid":int(request.POST["id"]),
               'access_token':request.session['comment_access_token'],
               "status":"Ok" }
    return HttpJSONResponse( result )    
  else:
    raise HttpNotImplemented

commentbin/templates/about.html
{% extends 'base.html' %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/css/about.css" />
{% endblock css %}

{% block content %}

<div id='thankyou'>
<h1> Thank You </h1>
<ul>
<li><a href='http://pygments.org'><img src='http://pygments.org/media/logo.png' alt='Pygments'/></a></li>
<li><a href='http://code.google.com/p/rangy/'>Rangy</a></li>
<li><a href='http://codemirror.net'><img src='http://codemirror.net/doc/baboon.png' alt='CodeMirror'/></a></li>
<li><a href='https://www.djangoproject.com/'><img src="{{ STATIC_URL }}commentbin/images/django.png" alt="Django"></a></li>
<li><a href='http://jquery.com'><img src="{{ STATIC_URL}}commentbin/images/jquery-logo.jpg" alt="jQuery: Write Less, Do More."></a></li>
<li><a href='http://blog.twg.ca/2010/11/retina-display-icon-set/'>Retina Icon Set </a></li>
<li><a href='http://twitter.github.com/bootstrap/index.html'><h3>Bootstrap</h3></a></li>
<li><a href='http://www.pythonanywhere.com'><img src='https://www.pythonanywhere.com/static/anywhere/images/logo-234x35.png' alt='PythonAnywhere'/></a></li>
</ul>
</div>

<h1> About <span class='logo-review gray'>Review</span><span class='logo-it gray'>It!</span></h1>

Review<i>It</i> is a 'pastebin'-like site which allows pasting snippets of (currently only) python code.
Users may attach inline comments to posted snippets. The site also offers three privacy modes for 
posted snippets:
<ul>
<li> Public &mdash; anyone can view and post comments,</li>
<li> Semi-public &mdash; anyone can view, only people knowing the password may comment and 
<li> Private &mdash; only people knowing the password may comment.</li>
</ul>
<h1> Features </h1>
<ul>
<li> Syntaxt hilighting </li>
<li> Inline comments </li>
<li> No need for signup/login </li>
<h2> Planned </h2>
<li> LaTeX rendering </li>
<li> PDF export </li>
</ul>
<h1> License </h1>
For the licenses of third-party included code, see the respective projects. All other code, unless otherwise stated,
is under the <a href='www.gnu.org/licenses/agpl-3.0.html'>GNU Affero General Public License (AGPLv3)</a>.

{% endblock content %}

commentbin/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% block css %}
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans:700|Henny+Penny&amp;text=ReviewIt!' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{{ STATIC_URL }}bootstrap-v2/css/bootstrap.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/css/base.css" />
    {% endblock %}
    
    {% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}commentbin/javascript/forms.js"></script>
    <script src="{{ STATIC_URL }}bootstrap-v2/js/bootstrap.js"></script>
    <script src="{{ STATIC_URL }}commentbin/javascript/collapse.js"></script>
    {% endblock %}
    
    <title>{% block title %}Commentbin{% endblock %}</title>
    

<script>
    {% block globalVars %}
    
    var static_url = "{{ STATIC_URL }}";
    
    formElements.push( { id:'header_nick',
                         related:'nick_related' } );
    
    {% endblock globalVars %}
function onReady() {
    {% block onReady %}
    {% endblock onReady %}
    $('.alert').addClass('fade')
    $('.alert').addClass('in')
    $('.alert').alert();
}
jQuery(document).ready(onReady);
</script>

</head>

<body>
<div id="header" class='navbar navbar-fixed-top'>
{% block header %}
<div class='header-control'>
    Hello,
{% if user.is_authenticated %}
    <b>{{ user.username }}! </b> <a href='{% url commentbin.views.logout %}'>Sign Out</a>
{% else %}
    <form class='header_nick'><input id='header_nick' class='header_nick nick_related' type='textinput' size="{{ nick|length }}" onClick='textInputClick(this);' onBlur='textInputLeave(this);' value='{{ nick|default:"anonymous" }}'/></form> 
       <!--<a href='{% url commentbin.views.login %}'>Login/Signup</a>-->
{% endif %}
<span id='header-links'>| <a href='{% url commentbin.views.about %}'> About </a>|<a href='{% url commentbin.views.sitehelp %}'> Help </a>|</span>
</div>
<h1><a href='{% url commentbin.views.index %}'><span class='logo-review'>Review</span><span class='logo-it'>It!</span></a></h1>

{% endblock header %}

</div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

commentbin/templates/index.html
{% extends "base.html" %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/css/newsnippet.css">
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/codemirror/lib/codemirror.css">
{% endblock css %}

{% block javascript %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}commentbin/codemirror/lib/codemirror.js"></script>
    <script src="{{ STATIC_URL }}commentbin/codemirror/mode/python/python.js"></script>
    
{% endblock javascript %}

{% block onReady %}

  {% autoescape off %}

  {{ block.super }}

  var myCodeMirror = CodeMirror.fromTextArea($('#id_code')[0],{
      lineNumbers:true
  });
  
  collapsible( $('#new_snippet_form_div')[0], $('#latest_snippets')[0], $('#new_snippet_collapse_control')[0], '50%');
  
  {% endautoescape %}
{% endblock onReady %}

{% block content %}
<div id='new_snippet_form_div'>
<div id='new_snippet_collapse_control' style='float:right'>
</div>
{% include "new_snippet_form.html" %}
</div>
<div id='latest_snippets'>
<h1 class='rightHeader'>Latest Snippets</h1>
{% if latest_snippets_list|length > 0 %}

  {% for snippet in latest_snippets_list %}
  <div class='snippet'>
      <a href='{% url commentbin.views.snippet snippet.id %}'>
        <h2>{% if snippet.title|length > 0 %} {{ snippet.title }} {% else %} Snippet #{{ snippet.id }} {% endif %}</h2>
      </a>  
       by <span class='nick'> {{ snippet.display_author }}</span> <span class='date'>(created at {{ snippet.creation_date|date:"SHORT_DATETIME_FORMAT" }})</span>
      </a>
  </div>
  {% endfor %}
{% else %}
  <p> No snippets available. </p>
{% endif %}
</div>

<div>


</div>


{% endblock content %}

commentbin/templates/new_snippet_form.html
<div id='new_snippet_form'>

<script>
 formElements.push( { id:'id_nick',
                      related:'nick_related' } );

 function setPrivacy(state) { 
   if (state === 'public') {
     $('.access_token_field').each( function () { this.style.display='none'; } );
     $('#id_public_comments')[0].checked='checked';
     $('#id_visible_to_public')[0].checked='checked';
   } else if ( state == 'semi_public' ) { 
     $('.access_token_field').each( function () { this.style.display='none'; } );
     var pass_field = $('.access_token_field.semi_public')[0];
     pass_field.style.display='block';
     pass_field.focus();
     $('#id_public_comments')[0].checked='';
     $('#id_visible_to_public')[0].checked='checked';
   } else if ( state == 'private' ) {
     $('.access_token_field').each( function () { this.style.display='none'; } );
     var pass_field = $('.access_token_field.private')[0];
     pass_field.style.display='block';
     pass_field.focus();
     $('#id_public_comments')[0].checked='';
     $('#id_visible_to_public')[0].checked='';
   }
 }
</script>

<form action="{% url commentbin.views.index %}" class = 'form-inline new_snippet_form' method='POST'>
{{ form.non_field_errors }}
<div>

<div class='formheader'>  
  <div style='float:left;'>
  {{ form.title }}
  </div>

  <div style='float:right'>
    {{ form.language }}
  <div style='display:none'>
  {% if user.is_authenticated %}
    {{ user.username }}
  {% else %}
    {{ form.nick }}
  {% endif %}
  </div>
  </div>
  <div style='clear:both;'></div>
</div>

<div class='formbody'>
  {{ form.title.errors }}
  {{ form.nick.errors }}


<div class='fieldWrapper codeArea'>
{{ form.code }}
</div>

<div style='float:right'><input type="submit" class='btn' value="New Snippet" /></div>
</div>
<div class='privacy_options'>
 <label for='id_public_comments'> <input type='radio' name='privacy' id='id_public'      onClick='setPrivacy("public")' checked='checked'  /><span>Public (anyone can view, anyone can comment)</span></label><br/>
 <label for='id_public_comments'> <input type='radio' name='privacy' id='id_semi_public' onClick='setPrivacy("semi_public")' />Private Commenting (anyone can view, people with password can comment)</label><br/>
 <div class='access_token_field semi_public' style='display:none'>
   <label for='id_public_token'>Password: {{ form.access_token }}</label> 
 </div>
 <label for='id_public_comments'> <input type='radio' name='privacy' id='id_private'     onClick='setPrivacy("private")'/>Private (only people with password can view and comment )</label><br/>
 <div class='access_token_field private' style='display:none'>
   <label for='id_public_token'>Password: {{ form.access_token }}</label> 
 </div>
 <div style='display:none'>
 <span class='lower'>{{ form.public_comments }}</span>
 <span class='lower'>{{ form.visible_to_public }}</span>
 <input type='hidden' name='language' id='id_language' value='py'/>
 </div>
</div>
</form>

</div>
</div> <!-- new_snippet_form -->

commentbin/templates/sitehelp.html
{% extends 'base.html' %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/css/about.css" />
{% endblock css %}

{% block content %}

<div class='coming-soon'> Coming soon ... </div>
{% endblock content %}

commentbin/templates/snippet-password.html
{% extends 'base.html' %}


{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{{ STATIC_URL }}commentbin/css/snippet-password.css" />
{% endblock css %}

{% block onReady %}
  $(document).bind('keydown','esc',function() { window.location="..";} );
{% endblock %}

{% block content %}

<div id='password_form' class='modal show password_form'>
<div class="modal-header">
    <h3>Password needed to view this snippet</h3>
</div>
  <div class="modal-body">
<form script='' method='GET'>
{% if wrong_password %}
 <div class='alert alert-error'> Invalid password, try again <a class='close' data-dismiss='alert' href='#'>×</a></div>
{% endif %}
<center>
<h4>Password<h4/>
<input type='textinput' class='passinput' value='Enter password here...' onClick='textInputClick(this);' name='access_token' />
</center>
  </div>
  <div class='modal-footer'>
    <input type='submit' value='Continue' class="btn">
    <input type='submit' onClick='window.location="..";return false;' value='Cancel' data-dismiss='#password_form' class="btn">
  </div>
</form>
</div> <!-- password_form -->
{% endblock content %}